### ISSUE TITLE
error while running flask

### ISSUE THREAD

**Issue by pierronaval** [inboxpraveen/LLM-Minutes-of-Meeting#2]
I've got this issue while lunchning flask 

(venv) PS C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting> flask run                              
Loading Speech Model...
[2024-01-04 17:54:51.920] [ctranslate2] [thread 52836] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.
Traceback (most recent call last):
  File "C:\Users\Pierre\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Pierre\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\lib\site-packages\flask\cli.py", line 1064, in main
    cli.main()
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\lib\site-packages\flask\cli.py", line 912, in run_command
    raise e from None
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\lib\site-packages\flask\cli.py", line 898, in run_command
    app = info.load_app()
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\lib\site-packages\flask\cli.py", line 313, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\venv\lib\site-packages\flask\cli.py", line 219, in locate_app
    __import__(module_name)
  File "C:\Users\Pierre\PycharmProjects\LLM-Minutes-of-Meeting\app.py", line 42, in <module>
    speech_pipeline = Faster_Whisper(MODEL_TO_RUN)
TypeError: __init__() should return None, not 'WhisperModel'

**Comment by djuillard** [comment]
Hi,

Same error here...

**Comment by sparvaneh** [comment]
It's the same error for me. I would appreciate any suggestions to solve the issue.
