### ISSUE TITLE
Issue with transformers and faster whisper

### ISSUE THREAD

**Issue by aman696** [inboxpraveen/LLM-Minutes-of-Meeting#4]
So its giving me error like transformer version needs 4.0 something and tokenizer version required is 1.9 for that but faster whisper needs tokenizer below 1.5. And as well getting the following error when running flask 
TypeError: __init__() should return None, not 'WhisperModel'

**Comment by santamanicka** [comment]
I got the same error when I run "flask run". Here's the error log:
Traceback (most recent call last):
  File "/Users/smanicka82/miniconda3/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/smanicka82/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 1105, in main
    cli.main()
  File "/Users/smanicka82/miniconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/smanicka82/miniconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smanicka82/miniconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smanicka82/miniconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smanicka82/miniconda3/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smanicka82/miniconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smanicka82/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 953, in run_command
    raise e from None
  File "/Users/smanicka82/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 937, in run_command
    app: WSGIApplication = info.load_app()
                           ^^^^^^^^^^^^^^^
  File "/Users/smanicka82/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 335, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smanicka82/miniconda3/lib/python3.11/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/Users/smanicka82/PycharmProjects/LLM-Minutes-of-Meeting/app.py", line 42, in <module>
    speech_pipeline = Faster_Whisper(MODEL_TO_RUN)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__() should return None, not 'WhisperModel'

**Comment by k-praveen-trellis** [comment]
Can you share your environment details, underlying python, and system details?
